version: "3"

services:
  postgres:
    container_name: tennis_db
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=$DBNAME
      - POSTGRES_USER=$PGUSER
      - POSTGRES_PASSWORD=$PGPASSWORD
    ports:
      - 1111:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
